name: recipe-api-drf

services:
  app:
    build:
      context: .
      args:
        - DEV=true # for DEV config
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=abc1234
    depends_on:
      - db

  db:
    image: postgres:14.13-alpine3.20
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=abc1234

volumes:
  dev-db-data: