---
# Used to perform Testing & Linting

name: Checks

on:
  push:
    branches: main

jobs:
  test-lint: # job ID
    name: Test and Lint
    runs-on: ubuntu-20.04 # docker-compose preinstalled with this OS
    steps:
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Checkout to latest code, so that GA have full access and can perform linting and testing
      - name: Checkout
        uses: actions/checkout@v4

      # Running unit tests
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"

      # Running linting
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"